# Generated by Django 6.0.1 on 2026-01-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_indexform'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shopform')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
            ],
        ),
    ]
